---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: street-java-bot-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: street-java-bot
  name: street-java-bot
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: street-java-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: street-java-bot
    app.openshift.io/runtime: python
  name: street-java-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-java-bot
  template:
    metadata:
      labels:
        app: street-java-bot
    spec:
      volumes:
        - name: street-java-bot-db-pvc
          persistentVolumeClaim:
            claimName: street-java-bot-db-pvc
      containers:
      - image: quay.io/atarazana/street-java-bot:1.0.0
        imagePullPolicy: Always
        name: street-java-bot
        volumeMounts:
            - name: street-java-bot-db-pvc
              mountPath: /db
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom: 
        - secretRef:
            name: street-java-bot-env
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: street-java-bot
  name: street-java-bot
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: street-java-bot
    weight: 100
