apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-gov
  name: app-gov
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-gov
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-gov
    app.openshift.io/runtime: python
  name: app-gov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gov
  template:
    metadata:
      labels:
        app: app-gov
    spec:
      containers:
      - image: quay.io/ansible_helm/slack-bot:1.0.0
        imagePullPolicy: Always
        name: app-gov
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom: 
        - secretRef:
            name: app-gov
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-gov
  name: app-gov
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: app-gov
    weight: 100
---
apiVersion: v1
kind: Secret
metadata:
  name: app-gov
  labels:
    app: app-gov
data:
  AAP_HOST: aHR0cHM6Ly9hYXBjdGwtZGVtby0xLmFwcHMub2NwNGNsdXN0ZXIub2NwNC5jZmVybmFuZC5jb20=
  AAP_USER: Nk1ISFN1NFpFZTk2SFJMbWdpMWlzZFhGT2hoRk1C
  AAP_PASS: Nk1ISFN1NFpFZTk2SFJMbWdpMWlzZFhGT2hoRk1C
  ARGOCD_ADMIN: YWRtaW4=
  ARGOCD_ADMIN_PASS: ckhDaUdFTHh3QkF0NGVrMGducHVYUTJVOXYxRmhZb2o=
  ARGOCD_HOST: aHR0cHM6Ly9hcmdvY2Qtc2VydmVyLXotZ2l0b3BzLmFwcHMub2NwNGNsdXN0ZXIub2NwNC5jZmVybmFuZC5jb20=
  SLACK_APP_TOKEN: eGFwcC0xLUEwNFJEU1hTOFBOLTQ4NzQwOTAwMDkzNDUtZWRhOTYwZmM1NWQ1YWYwOTNiZmE5MWRlMzcyYzVhZmE4NGJmYzhlNDBkODI5ZTUxOTQ1MzI3MTY2M2U0M2JiZA==
  SLACK_BOT_TOKEN: eG94Yi0zMzA5MDU5MzIzNzM0LTQ4NzQwODg4NDQxOTMtNGVVcm1aOW44ZTlrVkUzb2FwNmJnUFRB
  SLACK_SIGNING_SECRET: MjkyNjFjZDg4MmUxY2M5YzEyY2I0NmE2OTE4YjlmZjU=
type: Opaque
